### ISSUE TITLE
Bad SBC (ZP),Y  mnemonic code in mnemoniki[56] struct/array

### ISSUE THREAD

**Issue by seban-slt** [pkali/omc65#5]
there is a problem with ``sbc (zp),y`` mnemonic code, it assembles to: ``0xe1``, but should be ``0xf1`` mnemonic code.

you have:

``` {"sbc", 0, 0xff, 0xff, 0xff, 0xe9, 0xed, 0xe5, 0xfd, 0xf5, 0xf9, 0xff, 0xff, 0xe1, 0xff},```

but should be:

``` {"sbc", 0, 0xff, 0xff, 0xff, 0xe9, 0xed, 0xe5, 0xfd, 0xf5, 0xf9, 0xff, 0xff, 0xf1, 0xff},```

**Comment by ehn-pkalinowski** [comment]
Oh boy! I am so happy to see a bug report!!!!!  YAY!!!

**Comment by pkali** [comment]
YAY! A bug report!!!!!
